name: appenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - mysqlclient 
  - pip
  - pip:
      - python-dotenv
      - uvicorn[standard]
      - mysql-connector-python

